services:
  gymlog-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gymlog-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"
    volumes:
      - gymlog-db-data:/var/opt/mssql
    networks:
      - gymlog-network

  gymlog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gymlog-api
    depends_on:
      - gymlog-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=gymlog-db,1433;Database=GymLogDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False
    ports:
      - "8080:8080"
    networks:
      - gymlog-network

volumes:
  gymlog-db-data:

networks:
  gymlog-network:
    driver: bridge